import Ember from 'ember';
export const camelize = Ember.String.camelize;
export const capitalize = Ember.String.capitalize;
export const classify = Ember.String.classify;
export const dasherize = Ember.String.dasherize;
export const decamelize = Ember.String.decamelize;
export const fmt = Ember.String.fmt;
export const htmlSafe = Ember.String.htmlSafe;
export const loc = Ember.String.loc;
export const underscore = Ember.String.underscore;
export const w = Ember.String.w;
