import Ember from 'ember';
export const aliasMethod = Ember.aliasMethod;
export const computed = Ember.computed;
export const get = Ember.get;
export const getProperties = Ember.getProperties;
export const observer = Ember.observer;
export const set = Ember.set;
export const setProperties = Ember.setProperties;
export const trySet = Ember.trySet;
export default Ember.Object;
